# Fichier docker-compose.yml final, avec la correction de la variable BASEROW_PUBLIC_URL
version: "3.4"

services:
  caddy:
    image: caddy:2
    restart: unless-stopped
    environment:
      BASEROW_DOMAIN: ${BASEROW_DOMAIN:?}
      BASEROW_PUBLIC_URL: ${BASEROW_PUBLIC_URL:?}
      PRIVATE_WEB_FRONTEND_URL: http://web-frontend:3000
      PRIVATE_BACKEND_URL: http://backend:8000
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - media:/baserow/media
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - baserow_net

  backend:
    image: baserow/backend:1.34.2
    restart: unless-stopped
    environment:
      BASEROW_PUBLIC_URL: ${BASEROW_PUBLIC_URL:-https://${BASEROW_DOMAIN:?}}
      SECRET_KEY: ${SECRET_KEY:?}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:?}
      REDIS_PASSWORD: ${REDIS_PASSWORD:?}
      EMAIL_SMTP_HOST: ${EMAIL_SMTP_HOST:-}
      EMAIL_SMTP_PORT: ${EMAIL_SMTP_PORT:-587}
      EMAIL_SMTP_USE_TLS: ${EMAIL_SMTP_USE_TLS:-true}
      EMAIL_SMTP_USER: ${EMAIL_SMTP_USER:-}
      EMAIL_SMTP_PASSWORD: ${EMAIL_SMTP_PASSWORD:-}
      FROM_EMAIL: ${FROM_EMAIL:-}
      BASEROW_JWT_SIGNING_KEY: ${BASEROW_JWT_SIGNING_KEY:-}
      BASEROW_EXTRA_ALLOWED_HOSTS: ${BASEROW_EXTRA_ALLOWED_HOSTS:-}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-}
      AWS_STORAGE_BUCKET_NAME: ${AWS_STORAGE_BUCKET_NAME:-}
      AWS_S3_REGION_NAME: ${AWS_S3_REGION_NAME:-}
      AWS_S3_ENDPOINT_URL: ${AWS_S3_ENDPOINT_URL:-}
      BASEROW_BACKEND_DEBUG: ${BASEROW_BACKEND_DEBUG:-false}
      DATABASE_HOST: db
      DATABASE_NAME: ${DATABASE_NAME:-baserow}
      DATABASE_USER: ${DATABASE_USER:-baserow}
      REDIS_HOST: redis
      PRIVATE_BACKEND_URL: http://backend:8000
    volumes:
      - media:/baserow/media
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - baserow_net

  web-frontend:
    image: baserow/web-frontend:1.34.2
    restart: unless-stopped
    environment:
      BASEROW_PUBLIC_URL: ${BASEROW_PUBLIC_URL:-https://${BASEROW_DOMAIN:?}}
      PRIVATE_BACKEND_URL: http://backend:8000
    depends_on:
      backend:
        condition: service_started
    networks:
      - baserow_net

  celery:
    image: baserow/backend:1.34.2
    restart: unless-stopped
    command: celery-worker
    environment:
      BASEROW_PUBLIC_URL: ${BASEROW_PUBLIC_URL:-https://${BASEROW_DOMAIN:?}}
      SECRET_KEY: ${SECRET_KEY:?}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:?}
      REDIS_PASSWORD: ${REDIS_PASSWORD:?}
      EMAIL_SMTP_HOST: ${EMAIL_SMTP_HOST:-}
      EMAIL_SMTP_PORT: ${EMAIL_SMTP_PORT:-587}
      EMAIL_SMTP_USE_TLS: ${EMAIL_SMTP_USE_TLS:-true}
      EMAIL_SMTP_USER: ${EMAIL_SMTP_USER:-}
      EMAIL_SMTP_PASSWORD: ${EMAIL_SMTP_PASSWORD:-}
      FROM_EMAIL: ${FROM_EMAIL:-}
      BASEROW_JWT_SIGNING_KEY: ${BASEROW_JWT_SIGNING_KEY:-}
      BASEROW_EXTRA_ALLOWED_HOSTS: ${BASEROW_EXTRA_ALLOWED_HOSTS:-}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-}
      AWS_STORAGE_BUCKET_NAME: ${AWS_STORAGE_BUCKET_NAME:-}
      AWS_S3_REGION_NAME: ${AWS_S3_REGION_NAME:-}
      AWS_S3_ENDPOINT_URL: ${AWS_S3_ENDPOINT_URL:-}
      BASEROW_BACKEND_DEBUG: ${BASEROW_BACKEND_DEBUG:-false}
      DATABASE_HOST: db
      DATABASE_NAME: ${DATABASE_NAME:-baserow}
      DATABASE_USER: ${DATABASE_USER:-baserow}
      REDIS_HOST: redis
      PRIVATE_BACKEND_URL: http://backend:8000
    volumes:
      - media:/baserow/media
    depends_on:
      - backend
    networks:
      - baserow_net

  celery-export-worker:
    image: baserow/backend:1.34.2
    restart: unless-stopped
    command: celery-exportworker
    environment:
      BASEROW_PUBLIC_URL: ${BASEROW_PUBLIC_URL:-https://${BASEROW_DOMAIN:?}}
      SECRET_KEY: ${SECRET_KEY:?}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:?}
      REDIS_PASSWORD: ${REDIS_PASSWORD:?}
      EMAIL_SMTP_HOST: ${EMAIL_SMTP_HOST:-}
      EMAIL_SMTP_PORT: ${EMAIL_SMTP_PORT:-587}
      EMAIL_SMTP_USE_TLS: ${EMAIL_SMTP_USE_TLS:-true}
      EMAIL_SMTP_USER: ${EMAIL_SMTP_USER:-}
      EMAIL_SMTP_PASSWORD: ${EMAIL_SMTP_PASSWORD:-}
      FROM_EMAIL: ${FROM_EMAIL:-}
      BASEROW_JWT_SIGNING_KEY: ${BASEROW_JWT_SIGNING_KEY:-}
      BASEROW_EXTRA_ALLOWED_HOSTS: ${BASEROW_EXTRA_ALLOWED_HOSTS:-}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-}
      AWS_STORAGE_BUCKET_NAME: ${AWS_STORAGE_BUCKET_NAME:-}
      AWS_S3_REGION_NAME: ${AWS_S3_REGION_NAME:-}
      AWS_S3_ENDPOINT_URL: ${AWS_S3_ENDPOINT_URL:-}
      BASEROW_BACKEND_DEBUG: ${BASEROW_BACKEND_DEBUG:-false}
      DATABASE_HOST: db
      DATABASE_NAME: ${DATABASE_NAME:-baserow}
      DATABASE_USER: ${DATABASE_USER:-baserow}
      REDIS_HOST: redis
      PRIVATE_BACKEND_URL: http://backend:8000
    volumes:
      - media:/baserow/media
    depends_on:
      - backend
    networks:
      - baserow_net

  celery-beat-worker:
    image: baserow/backend:1.34.2
    restart: unless-stopped
    command: celery-beat
    environment:
      BASEROW_PUBLIC_URL: ${BASEROW_PUBLIC_URL:-https://${BASEROW_DOMAIN:?}}
      SECRET_KEY: ${SECRET_KEY:?}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:?}
      REDIS_PASSWORD: ${REDIS_PASSWORD:?}
      EMAIL_SMTP_HOST: ${EMAIL_SMTP_HOST:-}
      EMAIL_SMTP_PORT: ${EMAIL_SMTP_PORT:-587}
      EMAIL_SMTP_USE_TLS: ${EMAIL_SMTP_USE_TLS:-true}
      EMAIL_SMTP_USER: ${EMAIL_SMTP_USER:-}
      EMAIL_SMTP_PASSWORD: ${EMAIL_SMTP_PASSWORD:-}
      FROM_EMAIL: ${FROM_EMAIL:-}
      BASEROW_JWT_SIGNING_KEY: ${BASEROW_JWT_SIGNING_KEY:-}
      BASEROW_EXTRA_ALLOWED_HOSTS: ${BASEROW_EXTRA_ALLOWED_HOSTS:-}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-}
      AWS_STORAGE_BUCKET_NAME: ${AWS_STORAGE_BUCKET_NAME:-}
      AWS_S3_REGION_NAME: ${AWS_S3_REGION_NAME:-}
      AWS_S3_ENDPOINT_URL: ${AWS_S3_ENDPOINT_URL:-}
      BASEROW_BACKEND_DEBUG: ${BASEROW_BACKEND_DEBUG:-false}
      DATABASE_HOST: db
      DATABASE_NAME: ${DATABASE_NAME:-baserow}
      DATABASE_USER: ${DATABASE_USER:-baserow}
      REDIS_HOST: redis
      PRIVATE_BACKEND_URL: http://backend:8000
    volumes:
      - media:/baserow/media
    depends_on:
      - backend
    networks:
      - baserow_net

  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DATABASE_USER:-baserow}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:?}
      POSTGRES_DB: ${DATABASE_NAME:-baserow}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER:-baserow}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - baserow_net

  redis:
    image: redis:6
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD:?}
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD:?}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - baserow_net

  volume-permissions-fixer:
    image: bash:4.4
    command: chown 9999:9999 -R /baserow/media
    volumes:
      - media:/baserow/media
    restart: "no"
    networks:
      - baserow_net

volumes:
  pgdata:
  media:
  caddy_data:
  caddy_config:

networks:
  baserow_net:
    driver: bridge
